# Generated by Django 5.2.9 on 2025-12-13 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True, verbose_name='Slug')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True, verbose_name='Store name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/%Y/%m/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/%Y/%m/', verbose_name='Banner')),
                ('email', models.EmailField(max_length=254, verbose_name='Business email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Ward')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Country')),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual Seller'), ('business', 'Business'), ('brand', 'Official Brand Store')], default='individual', max_length=20, verbose_name='Vendor type')),
                ('business_license', models.CharField(blank=True, max_length=100, verbose_name='Business license number')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Commission rate')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total reviews')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Total products')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total orders')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total sales')),
                ('auto_confirm_orders', models.BooleanField(default=False, verbose_name='Auto confirm orders')),
                ('return_policy', models.TextField(blank=True, verbose_name='Return policy')),
                ('shipping_policy', models.TextField(blank=True, verbose_name='Shipping policy')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank name')),
                ('account_name', models.CharField(max_length=255, verbose_name='Account name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account number')),
                ('branch', models.CharField(blank=True, max_length=255, verbose_name='Branch')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default account')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Bank Account',
                'verbose_name_plural': 'Vendor Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('document_type', models.CharField(choices=[('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('id_card', 'ID Card'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=30, verbose_name='Document type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='vendors/documents/%Y/%m/', verbose_name='File')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Document',
                'verbose_name_plural': 'Vendor Documents',
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='vendors.vendorbankaccount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Payout',
                'verbose_name_plural': 'Vendor Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status', 'is_active'], name='vendors_ven_status_babeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['rating'], name='vendors_ven_rating_1e84ed_idx'),
        ),
    ]
