# Generated by Django 5.2.9 on 2025-12-13 12:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shipping_providers/', verbose_name='Logo')),
                ('provider_type', models.CharField(choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('viettel_post', 'Viettel Post'), ('vnpost', 'Vietnam Post'), ('jt', 'J&T Express'), ('best', 'BEST Express'), ('manual', 'Tự vận chuyển')], default='manual', max_length=50, verbose_name='Provider type')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API keys, endpoints, etc.', verbose_name='API Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default provider')),
                ('supported_countries', models.JSONField(blank=True, default=list, verbose_name='Supported countries')),
                ('min_delivery_days', models.PositiveIntegerField(default=1, verbose_name='Min delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(default=5, verbose_name='Max delivery days')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Shipping Provider',
                'verbose_name_plural': 'Shipping Providers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Zone name')),
                ('provinces', models.JSONField(default=list, help_text='List of province codes in this zone', verbose_name='Provinces')),
                ('districts', models.JSONField(blank=True, default=list, help_text='Specific district codes (optional)', verbose_name='Districts')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('api_service_code', models.CharField(blank=True, max_length=50, verbose_name='API service code')),
                ('min_delivery_days', models.PositiveIntegerField(default=1, verbose_name='Min delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(default=3, verbose_name='Max delivery days')),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Rate multiplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingprovider')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['provider', 'order'],
                'unique_together': {('provider', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Rate name')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base rate')),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min weight (kg)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max weight (kg)')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate per kg')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Min order value')),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Max order value')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Free shipping threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingprovider')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['provider', 'zone', 'min_weight'],
                'unique_together': {('provider', 'zone', 'min_weight')},
            },
        ),
    ]
