# Generated by Django 5.2.9 on 2025-12-13 16:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_product_stock_quantity_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('seasonal', 'Seasonal Promotion'), ('clearance', 'Clearance Sale'), ('new_arrival', 'New Arrival'), ('holiday', 'Holiday Special'), ('loyalty', 'Loyalty Reward'), ('referral', 'Referral Campaign'), ('email', 'Email Campaign'), ('social', 'Social Media'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_audience', models.JSONField(blank=True, default=dict, help_text='Target audience criteria (segments, locations, etc.)')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Campaign budget in VND', max_digits=12, null=True)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount spent so far', max_digits=12)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('banner_image', models.URLField(blank=True)),
                ('thumbnail_image', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = more prominent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='campaigns', to='products.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='campaigns', to='products.product')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('facebook', 'Facebook'), ('google', 'Google Ads'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('zalo', 'Zalo'), ('website', 'Website Banner'), ('app', 'In-App')], max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Channel-specific configuration')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_channels',
            },
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign Metrics',
                'db_table': 'campaign_metrics',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='campaigns_status_5500a9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'is_featured'], name='campaigns_campaig_021f5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignchannel',
            unique_together={('campaign', 'channel_type')},
        ),
    ]
