# Generated by Django 5.2.9 on 2025-12-13 15:43

import apps.base.core.uploads.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.base.core.uploads.models.upload_to_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'webm', 'mov'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('upload_type', models.CharField(choices=[('products', 'Product Image'), ('avatars', 'User Avatar'), ('vendors/logos', 'Vendor Logo'), ('vendors/documents', 'Vendor Document'), ('categories', 'Category Image'), ('banners', 'Banner Image'), ('blog', 'Blog Image'), ('documents', 'Document'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether file is referenced by another model')),
                ('used_by_model', models.CharField(blank=True, help_text='Model that references this upload (e.g., "Product", "User")', max_length=100)),
                ('used_by_id', models.CharField(blank=True, help_text='ID of the object that references this upload', max_length=100)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['upload_type', 'status'], name='uploads_upload__1d3a12_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='uploads_uploade_2ce21a_idx'), models.Index(fields=['is_used', 'is_deleted'], name='uploads_is_used_3d3109_idx')],
            },
        ),
    ]
