# Generated by Django 5.2.9 on 2025-12-13 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='Gender')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('driver', 'Driver'), ('support', 'Support Staff'), ('moderator', 'Moderator'), ('admin', 'Administrator')], db_index=True, default='customer', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='Staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email.', verbose_name='Verified')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone verified')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last activity')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notifications')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referral code')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=20, verbose_name='Address type')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient name')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Phone number')),
                ('street_address', models.CharField(max_length=500, verbose_name='Street address')),
                ('apartment', models.CharField(blank=True, max_length=100, verbose_name='Apartment/Unit')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Ward')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('city', models.CharField(max_length=100, verbose_name='City/Province')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='Session key')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Device type')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Device name')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating system')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last activity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('verification_type', models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('password_reset', 'Password Reset'), ('two_factor', 'Two Factor Authentication')], max_length=20, verbose_name='Verification type')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_user_email_3f6199_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
    ]
