# Generated by Django 5.2.9 on 2025-12-13 08:46

import apps.business.commerce.orders.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, default=apps.business.commerce.orders.models.generate_order_number, max_length=50, unique=True, verbose_name='Order number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30, verbose_name='Payment status')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Currency')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Discount')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Shipping')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tax')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Coupon code')),
                ('shipping_name', models.CharField(max_length=255, verbose_name='Shipping name')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Shipping phone')),
                ('shipping_address_line', models.TextField(verbose_name='Shipping address')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Shipping city')),
                ('shipping_country', models.CharField(default='Vietnam', max_length=100, verbose_name='Shipping country')),
                ('customer_note', models.TextField(blank=True, verbose_name='Customer note')),
                ('staff_note', models.TextField(blank=True, verbose_name='Staff note')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Source')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation reason')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product name')),
                ('product_sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('product_image', models.URLField(blank=True, verbose_name='Product image')),
                ('variant_name', models.CharField(blank=True, max_length=255, verbose_name='Variant')),
                ('selected_options', models.JSONField(blank=True, default=dict, verbose_name='Options')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Unit price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Discount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.15, max_digits=5, verbose_name='Commission rate')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Commission')),
                ('vendor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Vendor amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='Tracking number')),
                ('carrier', models.CharField(max_length=100, verbose_name='Carrier')),
                ('carrier_code', models.CharField(blank=True, max_length=50, verbose_name='Carrier code')),
                ('tracking_url', models.URLField(blank=True, verbose_name='Tracking URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='pending', max_length=30, verbose_name='Status')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped at')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Estimated delivery')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Weight (kg)')),
            ],
            options={
                'verbose_name': 'Order Shipment',
                'verbose_name_plural': 'Order Shipments',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('old_status', models.CharField(max_length=30, verbose_name='Old status')),
                ('new_status', models.CharField(max_length=30, verbose_name='New status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
