# Generated by Django 5.2.9 on 2025-12-13 08:46

import apps.business.commerce.payments.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Request')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='Icon')),
                ('gateway', models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('wallet', 'Owls Wallet'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50, verbose_name='Gateway')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Minimum amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Maximum amount')),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('both', 'Fixed + Percentage')], default='fixed', max_length=20, verbose_name='Fee type')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee amount')),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Fee percentage')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Refund number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('defective_product', 'Defective Product'), ('wrong_product', 'Wrong Product'), ('late_delivery', 'Late Delivery'), ('order_cancelled', 'Order Cancelled'), ('other', 'Other')], max_length=30, verbose_name='Reason')),
                ('reason_detail', models.TextField(blank=True, verbose_name='Reason detail')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway refund ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway response')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, default=apps.business.commerce.payments.models.generate_transaction_id, max_length=100, unique=True, verbose_name='Transaction ID')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=30, verbose_name='Status')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway response')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Error code')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
