# Generated by Django 5.2.9 on 2025-12-13 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('related_product_id', models.UUIDField()),
                ('co_purchase_count', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0, help_text='Confidence that these products are bought together')),
            ],
            options={
                'db_table': 'frequently_bought_together',
                'ordering': ['-co_purchase_count'],
                'indexes': [models.Index(fields=['product_id', '-co_purchase_count'], name='frequently__product_13668c_idx')],
                'unique_together': {('product_id', 'related_product_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('similar_product_id', models.UUIDField()),
                ('similarity_score', models.FloatField(help_text='Similarity score between 0 and 1')),
                ('category_match', models.BooleanField(default=False)),
                ('brand_match', models.BooleanField(default=False)),
                ('price_similarity', models.FloatField(default=0)),
                ('attribute_similarity', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'product_similarities',
                'ordering': ['-similarity_score'],
                'indexes': [models.Index(fields=['product_id', '-similarity_score'], name='product_sim_product_8b2ed6_idx')],
                'unique_together': {('product_id', 'similar_product_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_categories', models.JSONField(default=dict, help_text='Category ID -> preference score')),
                ('preferred_brands', models.JSONField(default=dict, help_text='Brand ID -> preference score')),
                ('avg_price_preference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attribute_preferences', models.JSONField(default=dict)),
                ('user_embedding', models.JSONField(default=list, help_text='User embedding vector for ML recommendations')),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='RecommendationClick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('recommendation_type', models.CharField(choices=[('similar', 'Similar Products'), ('frequently_bought', 'Frequently Bought Together'), ('also_viewed', 'Customers Also Viewed'), ('personalized', 'Personalized For You'), ('trending', 'Trending Now'), ('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('recently_viewed', 'Recently Viewed'), ('cart_based', 'Based On Your Cart'), ('wishlist_based', 'Based On Your Wishlist')], max_length=30)),
                ('source_product_id', models.UUIDField(blank=True, null=True)),
                ('clicked_product_id', models.UUIDField()),
                ('position', models.PositiveIntegerField(help_text='Position in recommendation list when clicked')),
                ('converted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_clicks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recommendation_type', '-created_at'], name='recommendat_recomme_35b4e9_idx'), models.Index(fields=['user', '-created_at'], name='recommendat_user_id_d49a33_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('similar', 'Similar Products'), ('frequently_bought', 'Frequently Bought Together'), ('also_viewed', 'Customers Also Viewed'), ('personalized', 'Personalized For You'), ('trending', 'Trending Now'), ('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('recently_viewed', 'Recently Viewed'), ('cart_based', 'Based On Your Cart'), ('wishlist_based', 'Based On Your Wishlist')], max_length=30)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('recommended_product_ids', models.JSONField(default=list)),
                ('scores', models.JSONField(default=list, help_text='Recommendation scores for each product')),
                ('expires_at', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_sets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recommendation_type', 'user'], name='recommendat_recomme_c298a3_idx'), models.Index(fields=['recommendation_type', 'product_id'], name='recommendat_recomme_2c5f4e_idx'), models.Index(fields=['expires_at', 'is_valid'], name='recommendat_expires_da1823_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('click', 'Clicked'), ('add_cart', 'Added to Cart'), ('add_wishlist', 'Added to Wishlist'), ('purchase', 'Purchased'), ('review', 'Reviewed'), ('share', 'Shared')], max_length=20)),
                ('interaction_weight', models.FloatField(default=1.0, help_text='Weight of this interaction for scoring')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_product_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_produc_user_id_6d8588_idx'), models.Index(fields=['product_id', '-created_at'], name='user_produc_product_8cb6bb_idx'), models.Index(fields=['user', 'interaction_type'], name='user_produc_user_id_675f15_idx')],
            },
        ),
    ]
