# Generated by Django 5.2.9 on 2025-12-13 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBoost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('search_term', models.CharField(blank=True, help_text='Apply boost when this term is searched', max_length=200)),
                ('boost_category', models.CharField(blank=True, max_length=100)),
                ('boost_product_ids', models.JSONField(default=list)),
                ('boost_factor', models.FloatField(default=1.5, help_text='Multiplier for relevance score')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'search_boosts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('category', 'Category'), ('brand', 'Brand'), ('price_range', 'Price Range'), ('rating', 'Rating'), ('attribute', 'Product Attribute'), ('availability', 'Availability')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('attribute_key', models.CharField(blank=True, help_text='For attribute filters, the attribute key to filter on', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'search_filters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=100)),
                ('synonyms', models.JSONField(default=list, help_text='List of synonymous terms')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='If True, synonyms work both ways')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'search_synonyms',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=200, unique=True)),
                ('suggestion_type', models.CharField(choices=[('popular', 'Popular Search'), ('trending', 'Trending'), ('curated', 'Manually Curated'), ('autocomplete', 'Autocomplete')], default='popular', max_length=20)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('click_through_count', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'search_suggestions',
                'ordering': ['-search_count', '-priority'],
                'indexes': [models.Index(fields=['term'], name='search_sugg_term_c6ad1c_idx'), models.Index(fields=['suggestion_type', 'is_active'], name='search_sugg_suggest_151d2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('query', models.CharField(max_length=500)),
                ('query_normalized', models.CharField(blank=True, max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_product_ids', models.JSONField(default=list)),
                ('category_filter', models.CharField(blank=True, max_length=100)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filters_applied', models.JSONField(default=dict)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query'], name='search_quer_query_50e46f_idx'), models.Index(fields=['user', '-created_at'], name='search_quer_user_id_486cee_idx'), models.Index(fields=['-created_at'], name='search_quer_created_824a49_idx')],
            },
        ),
    ]
