# Generated by Django 5.2.9 on 2025-12-13 08:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20, verbose_name='Discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount value')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage coupons', max_digits=15, null=True, verbose_name='Maximum discount')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Minimum order amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total usage limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='Usage limit per user')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Times used')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starts at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
