# Generated by Django 5.2.9 on 2025-12-13 15:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_product_stock_quantity_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_points', models.PositiveIntegerField(default=0, verbose_name='Minimum points required')),
                ('min_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Minimum total spent')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiply earned points (e.g., 1.5 = 50% bonus)', max_digits=4, verbose_name='Points multiplier')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Automatic discount for this tier', max_digits=5, verbose_name='Discount percentage')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Free shipping')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Priority support')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Color code')),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='loyalty/tiers/', verbose_name='Badge image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Loyalty Tier',
                'verbose_name_plural': 'Loyalty Tiers',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Current points')),
                ('points_earned_total', models.PositiveIntegerField(default=0, verbose_name='Total points earned')),
                ('points_spent_total', models.PositiveIntegerField(default=0, verbose_name='Total points spent')),
                ('points_expired_total', models.PositiveIntegerField(default=0, verbose_name='Total points expired')),
                ('tier_qualified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tier qualified at')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total orders')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total amount spent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='loyalty.loyaltytier')),
            ],
            options={
                'verbose_name': 'Loyalty Account',
                'verbose_name_plural': 'Loyalty Accounts',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('expired', 'Expired'), ('adjusted', 'Adjusted'), ('bonus', 'Bonus'), ('refund', 'Refund')], max_length=20, verbose_name='Type')),
                ('points', models.IntegerField(help_text='Positive for earned, negative for spent', verbose_name='Points')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Is expired')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('reward_type', models.CharField(choices=[('discount', 'Discount Voucher'), ('product', 'Free Product'), ('shipping', 'Free Shipping'), ('gift_card', 'Gift Card'), ('experience', 'Experience')], max_length=20, verbose_name='Type')),
                ('points_required', models.PositiveIntegerField(verbose_name='Points required')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Discount value')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount percentage')),
                ('quantity_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity available')),
                ('quantity_redeemed', models.PositiveIntegerField(default=0, verbose_name='Quantity redeemed')),
                ('redemption_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='Limit per user')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starts at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loyalty/rewards/', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('min_tier', models.ForeignKey(blank=True, help_text='Minimum tier required to redeem', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField(verbose_name='Points spent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Voucher code')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyaccount')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.reward')),
                ('used_on_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
