# Generated by Django 5.2.9 on 2025-12-13 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_product_stock_quantity_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g., order_confirmed, payment_received', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title_template', models.CharField(help_text='Use {variable} for placeholders', max_length=255, verbose_name='Title template')),
                ('body_template', models.TextField(help_text='Use {variable} for placeholders', verbose_name='Body template')),
                ('send_push', models.BooleanField(default=True, verbose_name='Send push notification')),
                ('send_email', models.BooleanField(default=False, verbose_name='Send email')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Send SMS')),
                ('category', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('promotion', 'Promotion'), ('account', 'Account'), ('system', 'System')], default='system', max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='Platform')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Device name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push notifications enabled')),
                ('push_order_updates', models.BooleanField(default=True, verbose_name='Order updates')),
                ('push_promotions', models.BooleanField(default=True, verbose_name='Promotions')),
                ('push_price_drops', models.BooleanField(default=True, verbose_name='Price drops')),
                ('push_back_in_stock', models.BooleanField(default=True, verbose_name='Back in stock')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email notifications enabled')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='Order updates via email')),
                ('email_promotions', models.BooleanField(default=False, verbose_name='Promotional emails')),
                ('email_newsletter', models.BooleanField(default=False, verbose_name='Newsletter')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS notifications enabled')),
                ('sms_order_updates', models.BooleanField(default=False, verbose_name='Order updates via SMS')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Quiet hours enabled')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Quiet hours start')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='Quiet hours end')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('notification_type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('promotion', 'Promotion'), ('account', 'Account'), ('system', 'System'), ('loyalty', 'Loyalty'), ('review', 'Review')], db_index=True, default='system', max_length=20, verbose_name='Type')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Action text')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push sent')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Push sent at')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='messaging_n_user_id_c93178_idx'), models.Index(fields=['user', 'is_read'], name='messaging_n_user_id_bd7d88_idx')],
            },
        ),
    ]
