# Generated by Django 5.2.9 on 2025-12-13 15:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('trigger_type', models.CharField(choices=[('page_load', 'On Page Load'), ('exit_intent', 'On Exit Intent'), ('scroll', 'On Scroll'), ('time_delay', 'After Time Delay'), ('cart_abandon', 'Cart Abandonment')], default='page_load', max_length=20)),
                ('trigger_delay', models.PositiveIntegerField(default=3, help_text='Seconds delay for time_delay trigger')),
                ('trigger_scroll_percent', models.PositiveIntegerField(default=50, help_text='Scroll percentage for scroll trigger')),
                ('show_once_per_session', models.BooleanField(default=True)),
                ('show_once_per_user', models.BooleanField(default=False)),
                ('cookie_duration_days', models.PositiveIntegerField(default=7)),
                ('target_pages', models.JSONField(default=list, help_text='List of page paths where popup should show')),
                ('exclude_logged_in', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'popup_banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('autoplay', models.BooleanField(default=True)),
                ('autoplay_speed', models.PositiveIntegerField(default=5000, help_text='Milliseconds')),
                ('transition_speed', models.PositiveIntegerField(default=500, help_text='Milliseconds')),
                ('pause_on_hover', models.BooleanField(default=True)),
                ('show_arrows', models.BooleanField(default=True)),
                ('show_dots', models.BooleanField(default=True)),
                ('infinite_loop', models.BooleanField(default=True)),
                ('slides_to_show', models.PositiveIntegerField(default=1)),
                ('slides_to_scroll', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Slider Settings',
                'db_table': 'slider_settings',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('banner_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('html', 'HTML Content')], default='image', max_length=20)),
                ('position', models.CharField(choices=[('hero_slider', 'Hero Slider'), ('homepage_top', 'Homepage Top'), ('homepage_middle', 'Homepage Middle'), ('homepage_bottom', 'Homepage Bottom'), ('category_top', 'Category Page Top'), ('product_sidebar', 'Product Sidebar'), ('cart_page', 'Cart Page'), ('checkout_page', 'Checkout Page'), ('popup', 'Popup Modal')], default='hero_slider', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Mobile version of banner (optional)', null=True, upload_to='banners/mobile/')),
                ('video_url', models.URLField(blank=True)),
                ('html_content', models.TextField(blank=True, help_text='Custom HTML for HTML type banners')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('overlay_color', models.CharField(blank=True, help_text='Hex color for overlay', max_length=7)),
                ('overlay_opacity', models.FloatField(default=0.3)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['position', 'order', '-created_at'],
                'indexes': [models.Index(fields=['position', 'is_active'], name='banners_positio_9fe3d8_idx'), models.Index(fields=['start_date', 'end_date'], name='banners_start_d_fb58be_idx')],
            },
        ),
    ]
