# Generated by Django 5.2.9 on 2025-12-13 15:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('velocity', 'Velocity Check'), ('amount', 'Amount Threshold'), ('ip', 'IP Address Check'), ('device', 'Device Fingerprint'), ('location', 'Geolocation Check'), ('behavior', 'Behavioral Analysis'), ('blacklist', 'Blacklist Check'), ('custom', 'Custom Rule')], db_index=True, max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text='Rule conditions in JSON format')),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('flag', 'Flag for Review'), ('block', 'Block'), ('challenge', 'Require Verification')], default='flag', max_length=20)),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='Risk score added when rule matches (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('priority', models.PositiveIntegerField(default=100, help_text='Rule evaluation priority (lower = evaluated first)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_rules',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['rule_type', 'is_active'], name='fraud_rules_rule_ty_a6744a_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(choices=[('fraud', 'Fraud Attempt'), ('abuse', 'Abuse/Spam'), ('bot', 'Bot Activity'), ('vpn', 'VPN/Proxy'), ('tor', 'Tor Exit Node'), ('manual', 'Manual Block')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for permanent block', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IP Blacklist',
                'db_table': 'ip_blacklist',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='Overall risk score (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], db_index=True, default='low', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed analysis results')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggeredRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_value', models.CharField(blank=True, help_text='The value that triggered this rule', max_length=255)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_triggers', to='fraud_detection.riskassessment')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='fraud_detection.fraudrule')),
            ],
            options={
                'db_table': 'triggered_rules',
                'unique_together': {('assessment', 'rule')},
            },
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='triggered_rules',
            field=models.ManyToManyField(related_name='assessments', through='fraud_detection.TriggeredRule', to='fraud_detection.fraudrule'),
        ),
        migrations.CreateModel(
            name='VelocityCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter_type', models.CharField(choices=[('order_user', 'Orders by User'), ('order_ip', 'Orders by IP'), ('order_card', 'Orders by Card'), ('login_user', 'Logins by User'), ('login_ip', 'Logins by IP'), ('failed_payment', 'Failed Payments')], db_index=True, max_length=30)),
                ('identifier', models.CharField(db_index=True, help_text='User ID, IP address, or card hash', max_length=255)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for this window (for orders)', max_digits=12)),
            ],
            options={
                'db_table': 'velocity_counters',
                'indexes': [models.Index(fields=['counter_type', 'identifier', 'window_end'], name='velocity_co_counter_383d49_idx')],
                'unique_together': {('counter_type', 'identifier', 'window_start')},
            },
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk_level', 'status'], name='risk_assess_risk_le_598d83_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['user', 'created_at'], name='risk_assess_user_id_2a6f39_idx'),
        ),
    ]
